/*
 * This file is generated by jOOQ.
 */
package com.example.db;


import com.example.db.tables.LateOrders;
import com.example.db.tables.records.LateOrdersRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LateOrdersRecord> LATE_ORDERS_PKEY = UniqueKeys0.LATE_ORDERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<LateOrdersRecord> LATE_ORDERS_PKEY = Internal.createUniqueKey(LateOrders.LATE_ORDERS, "late_orders_pkey", LateOrders.LATE_ORDERS.ID);
    }
}
