/*
 * This file is generated by jOOQ.
 */
package com.example.db;


import com.example.db.tables.LateOrders;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.late_orders</code>.
     */
    public static final LateOrders LATE_ORDERS = com.example.db.tables.LateOrders.LATE_ORDERS;
}
